/*
===================================================================================
CLOUD SQL FOR POSTGRESQL: DATABASE & SCHEMA BOOTSTRAP
===================================================================================
*/

-- 0. DATABASE CREATION
SELECT 'CREATE DATABASE search'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'search')\gexec

\c search

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS vector CASCADE;
CREATE EXTENSION IF NOT EXISTS google_ml_integration CASCADE;

-- 2. TABLES
DROP TABLE IF EXISTS user_prompt_history CASCADE;

CREATE TABLE public.user_prompt_history (
    id SERIAL PRIMARY KEY,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_prompt text,
    prompt_embedded public.vector(3072),
    query_template_used boolean,
    query_template_id integer,
    query_explanation text
);

DROP TABLE IF EXISTS property_listings CASCADE;
CREATE TABLE property_listings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    bedrooms INT,
    city VARCHAR(100),
    image_gcs_uri TEXT,
    country VARCHAR(100) DEFAULT 'Switzerland',
    canton VARCHAR(100),
    description_embedding vector(3072),
    image_embedding vector(1408) 
);

-- 3. INDEX CREATION 
-- follow seperate index.sql file or automatically as part of the install_databases.sh script

-- 4. IAM GRANTS
-- Grant access to all current and future tables/sequences in the public schema to all users (including IAM users)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO PUBLIC;

-- 3. Test Text Embeddings in Database Vertex AI integration
SELECT google_ml.embedding(
    model_id => 'gemini-embedding-001',
    content => 'This is the text to embed.'
);
