/*
===================================================================================
CLOUD SQL FOR POSTGRESQL: DATABASE & SCHEMA BOOTSTRAP
===================================================================================
*/

-- 0. DATABASE CREATION
SELECT 'CREATE DATABASE search'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'search')\gexec

\c search

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS vector CASCADE;
CREATE EXTENSION IF NOT EXISTS google_ml_integration CASCADE;

-- 2. TABLES
DROP TABLE IF EXISTS user_prompt_history CASCADE;

CREATE TABLE public.user_prompt_history (
    id SERIAL PRIMARY KEY,
    "timestamp" timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    user_prompt text,
    prompt_embedded public.vector(3072),
    query_template_used boolean,
    query_template_id integer,
    query_explanation text
);

DROP TABLE IF EXISTS property_listings CASCADE;
CREATE TABLE property_listings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC NOT NULL,
    bedrooms INT,
    city VARCHAR(100),
    image_gcs_uri TEXT,
    country VARCHAR(100) DEFAULT 'Switzerland',
    canton VARCHAR(100),
    description_embedding vector(3072),
    image_embedding vector(1408) 
);

-- 3. INDEX CREATION 
-- follow seperate index.sql file or automatically as part of the install_databases.sh script

-- 4. IAM GRANTS
-- Revoke default public access
REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA public FROM PUBLIC;
REVOKE ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM PUBLIC;

-- Grant access to the service account user
GRANT USAGE ON SCHEMA public TO "search-backend-sa@{PROJECT_ID}.iam";
GRANT SELECT ON TABLE property_listings TO "search-backend-sa@{PROJECT_ID}.iam";
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_prompt_history TO "search-backend-sa@{PROJECT_ID}.iam";
GRANT USAGE, SELECT ON SEQUENCE user_prompt_history_id_seq TO "search-backend-sa@{PROJECT_ID}.iam";

-- 3. Register Multimodal Embedding Model, because it is not available as built-in model
CREATE OR REPLACE FUNCTION multimodal_input_transform(model_id VARCHAR(100), input_text TEXT)
RETURNS JSON AS $$
BEGIN
    RETURN json_build_object(
        'instances', json_build_array(
            json_build_object('text', input_text)
        )
    );
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION multimodal_output_transform(model_id VARCHAR(100), response_json JSON)
RETURNS real[] AS $$
BEGIN
    RETURN (
        SELECT array_agg(value::real)
        FROM json_array_elements_text(
            response_json->'predictions'->0->'textEmbedding'
        )
    );
END;
$$ LANGUAGE plpgsql;

CALL google_ml.create_model(
    model_id => 'multimodalembedding@001',
    model_provider => 'google',
    model_type => 'text_embedding',
    model_qualified_name => 'multimodalembedding@001',
    model_auth_type => 'cloudsql_service_agent_iam',
    model_in_transform_fn => 'multimodal_input_transform',
    model_out_transform_fn => 'multimodal_output_transform'
);

-- 4. Test Text Embeddings in Database Vertex AI integration
SELECT google_ml.embedding(
    model_id => 'gemini-embedding-001',
    content => 'This is the text to embed.'
);

-- 5. Test Multimodal Embeddings in Database Vertex AI integration
SELECT google_ml.embedding(
    model_id => 'multimodalembedding@001',
    content => 'This is the text to embed.'
);
